name: "Run Java Code"
on:
  push:
    branches:
      - main
jobs:
 run_java_code:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - run: |
         javac Main.java
         java Main
